---
apiVersion: v1
kind: Secret
metadata:
  name: microos
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    secrets=$(dirname $0)
    transactional-update --continue cleanup dup
    # For a delayed reboot use:
    #   rebootmgrctl reboot
    # or chain it with transactional-update commands:
    #   transactional-update --continue cleanup dup reboot
    [ -f /run/reboot-needed ] && rebootmgrctl reboot now
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: microos
  namespace: system-upgrade
spec:
  concurrency: 2
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/worker, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  secrets:
    - name: microos
      path: /host/run/system-upgrade/secrets/microos
  drain:
    force: true
  version: microos
  upgrade:
    image: registry.opensuse.org/opensuse/tumbleweed:latest
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/microos/upgrade.sh"]
